<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AutoCADTools.Presentation</RootNamespace>
    <AssemblyName>AutoCADTools.Presentation</AssemblyName>
    <UseWpf>true</UseWpf>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System"/>
    <Reference Include="System.Core"/>
    <Reference Include="System.Data"/>
    <Reference Include="System.Xml"/>
    <Reference Include="System.ComponentModel.DataAnnotations"/>
    <Reference Include="System.Runtime.Serialization"/>
    <Reference Include="PresentationCore"/>
    <Reference Include="PresentationFramework"/>
    <Reference Include="WindowsBase"/>
    <Reference Include="System.Windows.Forms"/>
    <Reference Include="WindowsFormsIntegration"/>
  </ItemGroup>

  <!-- AutoCAD DLL references -->
  <ItemGroup>
    <Reference Include="accoremgd">
      <HintPath>$(ProgramFiles)\Autodesk\AutoCAD $(AutodeskVersion)\accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgd">
      <HintPath>$(ProgramFiles)\Autodesk\AutoCAD $(AutodeskVersion)\acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgdbrep">
      <HintPath>$(ProgramFiles)\Autodesk\AutoCAD $(AutodeskVersion)\acdbmgdbrep.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acmgd">
      <HintPath>$(ProgramFiles)\Autodesk\AutoCAD $(AutodeskVersion)\acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMPolygonMGD">
      <HintPath>$(ProgramFiles)\Autodesk\AutoCAD $(AutodeskVersion)\AcMPolygonMGD.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>$(ProgramFiles)\Autodesk\AutoCAD $(AutodeskVersion)\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoCADTools.Core\AutoCADTools.Core.csproj"/>
    <ProjectReference Include="..\AutoCADTools.Service\AutoCADTools.Service.csproj"/>
    <ProjectReference Include="..\AutoCADTools.Storage\AutoCADTools.Storage.csproj"/>
  </ItemGroup>

  <!-- NuGet packages -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5"/>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="All"/>
    <PackageReference Include="Wpf.Controls.PanAndZoom" Version="2.0.0" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Canvas\LineWeightData\LineWeightData.json" />
  </ItemGroup>

</Project>
