//------------------------------------------------------------------------------
// <auto-generated>
//   This file provides sample usage of the Canvas module.
//   Uncomment sections as needed for testing.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Autodesk.AutoCAD.ApplicationServices.Core;
using AutoCADTools.Presentation.Canvas;
using AutoCADTools.Presentation.Canvas.Annotation;
using Autodesk.AutoCAD.Runtime;

namespace AutoCADTools.App
{
  public static class CanvasDemo
  {
    /// <summary>
    /// Creates a CanvasView with sample annotations for testing.
    /// </summary>
    /// <returns>
    /// Tuple of (CanvasView, CanvasViewModel). The Canvas is already wired to ZoomBorder via WindowLoadedCommand.
    /// </returns>
    public static (CanvasView view, Presentation.Canvas.CanvasViewModel vm) CreateDemoCanvas()
    {
      var (view, vm) = CreateCanvasView();
      AddSampleAnnotations(vm.Canvas!);
      AppEntry.RegisterViewModel(vm);
      return (view, vm);
    }

    /// <summary>
    /// Creates the CanvasView and triggers WindowLoadedCommand to wire Canvas + ZoomBorder.
    /// </summary>
    private static (CanvasView view, Presentation.Canvas.CanvasViewModel vm) CreateCanvasView()
    {
      var vm = new Presentation.Canvas.CanvasViewModel();
      var view = new CanvasView { DataContext = vm };
      return (view, vm);
    }

    /// <summary>
    /// Adds sample annotations to the Canvas for visual testing.
    /// Call after CreateCanvasView so vm.Canvas is populated.
    /// </summary>
    public static void AddSampleAnnotations(Canvas canvas)
    {
      if (canvas == null)
        return;

      // Grid2D
      new Grid2D(canvas, scale: 1.0, name: "A", startPoint: new Point(50, 50),
        endPoint: new Point(300, 50),
        symbolStyleAtStart: EnumGridSymbolStyle.Circle,
        symbolStyleAtEnd: EnumGridSymbolStyle.TextOnly);

      // Grid2D horizontal axis
      new Grid2D(canvas, scale: 1.0, name: "B", startPoint: new Point(50, 50),
        endPoint: new Point(50, 400),
        symbolStyleAtStart: EnumGridSymbolStyle.Circle,
        symbolStyleAtEnd: EnumGridSymbolStyle.Oval);

      // Arrow2D
      new Arrow2D(canvas, scale: 1.0,
        startPoint: new Point(100, 100),
        endPoint: new Point(250, 150),
        lineType: Presentation.Canvas.Shapes.EnumLineType.Solid,
        symbolStyleAtStart: EnumArrowHeadStyle.Dot,
        symbolStyleAtEnd: EnumArrowHeadStyle.ArrowFilled,
        lineWeightId: 3,
        color: Brushes.Navy);

      // Hatch2D
      var points = new PointCollection {
        new Point(350, 80), new Point(450, 80),
        new Point(450, 150), new Point(350, 150)
      };
      new Hatch2D(canvas, scale: 1.0, points: points,
        lineThickness: 1.5,
        lineColor: Brushes.Green,
        fillColor: Brushes.LightGreen,
        text: "HATCH");

      // TextNote2D
      new TextNote2D(canvas, scale: 1.0, text: "Sample Text",
        textFontSize: 5, position: new Point(200, 300),
        textColor: Brushes.Black, angle: 15);

      var ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument?.Editor;
      ed?.WriteMessage($"\n[CanvasDemo] Added {canvas.Children.Count} annotations.");
    }
  }
}
