//------------------------------------------------------------------------------
// <auto-generated>
//   This file provides sample usage of the Canvas module.
//   Uncomment sections as needed for testing.
// </auto-generated>
//------------------------------------------------------------------------------

// using System.Windows;
// using System.Windows.Controls;
// using System.Windows.Media;
// using AutoCADTools.Presentation.Canvas;
// using AutoCADTools.Presentation.Canvas.Annotation;
// using Microsoft.Extensions.DependencyInjection;
//
// namespace AutoCADTools.App
// {
//   public static class CanvasDemo
//   {
//     /// <summary>
//     /// Creates a CanvasView with sample annotations for testing.
//     /// </summary>
//     public static (CanvasView view, CanvasViewModel vm) CreateDemoCanvas()
//     {
//       var container = new ServiceCollection();
//       container.AddTransient<CanvasViewModel>();
//       using var sp = container.BuildServiceProvider();
//
//       var vm = sp.GetRequiredService<CanvasViewModel>();
//       var view = new CanvasView { DataContext = vm };
//
//       // Sample: add a Grid2D annotation
//       // var canvas = new Canvas { Width = 800, Height = 600 };
//       // new Grid2D(canvas, scale: 1.0, name: "A", startPoint: new Point(50, 50), endPoint: new Point(300, 50),
//       //   symbolStyleAtStart: EnumGridSymbolStyle.Circle, symbolStyleAtEnd: EnumGridSymbolStyle.Circle);
//
//       return (view, vm);
//     }
//   }
// }
